name: Rust By Ceppelli Github Pages Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir mdbook
        MDBOOK_VERSION=v0.4.25
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Deploy GitHub Pages
      run: |
        # This assumes your book is in the root of your repository.
        # Just add a `cd` here if you need to change to another directory.
        cd book
        mdbook build
        echo "mdbook build completed."
        git worktree add gh-pages
        echo "worktree add gh-page completed."
        git config user.name "Deploy from CI"
        git config user.email ""
        echo "git config completed."
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        echo "git update-ref completed."
        rm -rf *
        mv ../book/* .
        echo "git mv completed."
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        echo "git commit completed."
        git push --force --set-upstream origin gh-pages
        echo "git push completed."
